### ISSUE TITLE
想问下博主是18sp&21sp都做了吗

### ISSUE THREAD

**Issue by Diane513** [half-dreamer/CS61B-18sp#1]
想问下博主是18sp&21sp都做了吗？

**Comment by half-dreamer** [comment]
都做了一部分，18sp做的是算法的，21sp做的是Java部分的，基本大部分都做了；
平时不怎么看邮件，回复慢了

Diane513 ***@***.***> 于2023年8月7日周一 14:42写道：

**Comment by Diane513** [comment]
谢谢回答~ 方便问下为什么做了一年的版本之后，还选择再做另一年的？

**Comment by half-dreamer** [comment]
闲的（x）
因为18sp的作业里更注重算法，21sp的作业里更多的是Java，如果你要选一个，我建议你做18sp的

Diane513 ***@***.***> 于2023年8月12日周六 16:35写道：

**Comment by Diane513** [comment]
谢谢回答！
